#!/usr/bin/env bash
#----------------------------------------------------------------------------
# Script : run_tb.sh
# Purpose: compile and run one self-checking XSim testbench from tb/.
#
#   tools/run_tb.sh <tb_name> [xsim args...]
#
#   tools/run_tb.sh tb_cordic_arctan
#   tools/run_tb.sh tb_cordic_arctan --testplusarg DUMP_CSV   (per-config CSV)
#   DUMP=1 tools/run_tb.sh tb_cordic_arctan                   (`define DUMP -> VCD)
#   make tb                                                   (every tb/tb_*.v)
#   make tb TB=tb_cordic_arctan [XSIM_ARGS="--testplusarg QUICK"]
#
# What it does
#   * sources the Vivado settings ($VIVADO_SETTINGS, default
#     /tools/2025.2/Vivado/settings64.sh) when xvlog is not on PATH,
#   * compiles ONLY the RTL each bench needs (the case below is the list -
#     never dot11 & co), the bench itself and, where a bench compares
#     against a Xilinx IP, the IP funcsim netlist (xelab -L unisims_ver, glbl
#     as second top). The cmpy netlist's wrapper module is called
#     complex_multiplier, which clashes with our replacement of the same
#     name, so it is copied into the build directory with the wrapper
#     renamed to cmpy_xilinx_ref (anchored sed on the "module" line only;
#     the inner, encrypted modules keep their names),
#   * runs in build/tb/<tb>/ (fresh xsim.dir each time), writes
#     build/tb/<tb>/<tb>.log and exits non-zero unless the log holds a
#     "RESULT: PASS" line and no "RESULT: FAIL" line.
#
# Every source file gets its own xvlog call: xvlog keeps `define macros
# across the files of one invocation, so an include guard (cordic_arctan.vh
# has one) would hide the include from every file after the first.
#
# Notes for bench authors
#   * -i <rtl dir> is passed to every xvlog call (`include "x.vh" resolves).
#   * LUT_DIR="<rtl dir>" is defined for the benches that pull lut_roms.v.
#   * The funcsim netlists carry `timescale 1ps/1ps and their own glbl with
#     ROC_WIDTH = 100000 ps: Xilinx primitives are held in reset for the
#     first 100 ns of simulated time - do not stimulate the IP before that.
#   * The IP netlists are regenerated by `make check` (gitignored); the
#     script tells you which one is missing.
#
# Environment overrides (mainly for A/B experiments):
#   RTL_DIR (default <repo>/verilog), TB_DIR (<repo>/tb), IP_DIR (<repo>/ip_repo)
#
# Project: RA-Sentinel (NLnet) - fork of openofdm,
#          https://github.com/Tobias-DG3YEV/openofdm
# Engineer: Tobias Weber
#----------------------------------------------------------------------------
# Copyright 2026 Tobias Weber
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#----------------------------------------------------------------------------
set -eEuo pipefail   # -E: the ERR trap below must also fire inside run()

usage() {
    echo "usage: $0 <tb_name> [xsim args...]" >&2
    echo "       tb_name: tb_cordic_arctan | tb_complex_multiplier | tb_phase" >&2
    exit 2
}

TB="${1:-}"
[ -n "$TB" ] || usage
shift

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RTL_DIR="${RTL_DIR:-$ROOT/verilog}"
TB_DIR="${TB_DIR:-$ROOT/tb}"
IP_DIR="${IP_DIR:-$ROOT/ip_repo}"
BUILD="$ROOT/build/tb/$TB"
LOG="$BUILD/$TB.log"

# --- Vivado on PATH ---------------------------------------------------------
if ! command -v xvlog >/dev/null 2>&1; then
    VIVADO_SETTINGS="${VIVADO_SETTINGS:-/tools/2025.2/Vivado/settings64.sh}"
    if [ ! -r "$VIVADO_SETTINGS" ]; then
        echo "run_tb.sh: xvlog not on PATH and $VIVADO_SETTINGS not found" >&2
        exit 2
    fi
    # settings64.sh reads unset variables (PYTHONPATH) and is not written for
    # errexit/nounset: relax both while it runs.
    set +eu
    # shellcheck disable=SC1090
    source "$VIVADO_SETTINGS"
    set -eu
    command -v xvlog >/dev/null 2>&1 || {
        echo "run_tb.sh: xvlog still not on PATH after sourcing $VIVADO_SETTINGS" >&2
        exit 2
    }
fi
XILINX_VIVADO="${XILINX_VIVADO:-$(cd "$(dirname "$(command -v xvlog)")/.." && pwd)}"

# --- per-bench source lists ------------------------------------------------
RTL=()          # RTL under test + what it instantiates
NETLIST=()      # Xilinx funcsim netlists / IP HDL (elaborated with -L unisims_ver)
DEFINES=()      # extra xvlog -d options
case "$TB" in
    tb_cordic_arctan)
        RTL=("$RTL_DIR/cordic_arctan.v")
        ;;
    tb_complex_multiplier)
        RTL=("$RTL_DIR/complex_multiplier.v")
        NETLIST=("$BUILD/cmpy_xilinx_ref.v")     # renamed copy, created below
        ;;
    tb_phase)
        RTL=("$RTL_DIR/cordic_arctan.v"
             "$RTL_DIR/phase.v"
             "$RTL_DIR/delayT.v"
             "$RTL_DIR/divider.v"
             "$RTL_DIR/div_gen.v"
             "$RTL_DIR/lut_roms.v"
             "$TB_DIR/phase_divlut_ref.v")
        NETLIST=("$IP_DIR/div_gen/div_gen_div_gen_0_0_sim_netlist.v"
                 "$IP_DIR/div_gen_xlslice/synth/div_gen_xlslice_0_0.v"
                 "$XILINX_VIVADO/data/ip/xilinx/xlslice_v1_0/hdl/xlslice_v1_0_vl_rfs.v")
        DEFINES=(-d "LUT_DIR=\"$RTL_DIR\"")
        ;;
    *)
        echo "run_tb.sh: unknown bench '$TB'" >&2
        usage
        ;;
esac

# --- build directory, log --------------------------------------------------
rm -rf "$BUILD/xsim.dir"
mkdir -p "$BUILD"
: > "$LOG"
cd "$BUILD"

log() { echo "$*" | tee -a "$LOG"; }
run() {
    log "+ $*"
    "$@" 2>&1 | tee -a "$LOG"
}
trap 'echo "### run_tb.sh: $TB FAILED (see $LOG)" | tee -a "$LOG"; exit 1' ERR

log "### run_tb.sh $TB  $(date '+%Y-%m-%d %H:%M:%S')  root=$ROOT"

if [ "$TB" = "tb_complex_multiplier" ]; then
    src="$IP_DIR/complex_multiplier/complex_multiplier_sim_netlist.v"
    if [ ! -r "$src" ]; then
        log "run_tb.sh: missing IP funcsim netlist $src (run 'make check' to regenerate)"
        false
    fi
    sed 's/^module complex_multiplier$/module cmpy_xilinx_ref/' "$src" > "$BUILD/cmpy_xilinx_ref.v"
    grep -q '^module cmpy_xilinx_ref' "$BUILD/cmpy_xilinx_ref.v" || {
        log "run_tb.sh: rename of the cmpy wrapper module failed"; false; }
    log "### cmpy funcsim netlist copied to $BUILD/cmpy_xilinx_ref.v (module cmpy_xilinx_ref)"
fi

for f in "${RTL[@]}" ${NETLIST[@]+"${NETLIST[@]}"} "$TB_DIR/$TB.v"; do
    if [ ! -r "$f" ]; then
        log "run_tb.sh: missing source file $f"
        false
    fi
done

# --- compile (one xvlog call per file, see header) -------------------------
for f in "${RTL[@]}"; do
    run xvlog -i "$RTL_DIR" ${DEFINES[@]+"${DEFINES[@]}"} "$f"
done
for f in ${NETLIST[@]+"${NETLIST[@]}"}; do
    run xvlog "$f"
done
DUMP_DEF=()
if [ -n "${DUMP:-}" ]; then
    DUMP_DEF=(-d DUMP)
fi
run xvlog -i "$RTL_DIR" ${DEFINES[@]+"${DEFINES[@]}"} ${DUMP_DEF[@]+"${DUMP_DEF[@]}"} \
    "$TB_DIR/$TB.v"

# --- elaborate -------------------------------------------------------------
ELAB=(xelab --snapshot "${TB}_snap" --timescale 1ns/1ps -L work)
if [ ${#NETLIST[@]} -gt 0 ]; then
    ELAB+=(-L unisims_ver "work.$TB" work.glbl)
else
    ELAB+=("work.$TB")
fi
run "${ELAB[@]}"

# --- simulate --------------------------------------------------------------
run xsim "${TB}_snap" -R "$@"

# --- verdict ---------------------------------------------------------------
trap - ERR
if grep -q "RESULT: PASS" "$LOG" && ! grep -q "RESULT: FAIL" "$LOG"; then
    log "### run_tb.sh: $TB PASS  ($LOG)"
    exit 0
fi
log "### run_tb.sh: $TB FAIL  ($LOG)"
grep "RESULT" "$LOG" || log "### run_tb.sh: no RESULT line in the log"
exit 1
